server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GloryH0828/spring_cloud_demo.git
          search-paths: config
          username: GloryH0828
          password: qq2453443152
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/